spring:
  datasource:
    url: jdbc:h2:mem:cryptodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true   # ⬅️ THÊM DÒNG NÀY
  sql:
    init:
      mode: always
server:
  port: 8080
